name: Python package

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry==1.7.1
          poetry install --with lint
      - name: Run pylint
        run: poetry run pylint pytest_docker_service
      - name: Run mypy
        run: poetry run mypy

  test:
    needs: lint
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "20.10"
          docker_channel: stable
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry==1.7.1
          poetry install --with tests
      - name: Run pytest
        run: poetry run pytest
